[package]
name = "zk_ecdsa"
type = "bin"
authors = [" Suraj Yadav "]

# Nargo.toml

[dependencies]
ecrecover = { tag = "v0.30.0", git = "https://github.com/colinnielsen/ecrecover-noir" }
keccak256 = { tag = "v0.1.0", git = "https://github.com/noir-lang/keccak256" }
